import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SessionProvider from '@/lib/sessionProvider';
import ReactToast from '@/components/ReactToast';
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <Navbar />
          <div className="px-6 md:px-16 lg:px-24 xl:px-32 py-4">{children}</div>
          <ReactToast />
        </body>
      </SessionProvider>
    </html>
  );
}
